### PR TITLE
add necessary exports

### PR DESCRIPTION
**Pull request by sanekyy**

### CODE REVIEW

**Comment by happy-san** [comment]
Hey @sanekyy, Thanks for your contribution.
Could you elaborate on your use case and why you'd need direct access to the classes defined in these files?

**Comment by sanekyy** [comment]
I need to have method like this:
```dart
Collection typesenseCollection() {
    return TypesenseRepository.client.collection('collectionName');
}
  ```

**Comment by happy-san** [comment]
Okay, thanks for sharing.

**Comment by sanekyy** [comment]
Hey! When will you publish new version of package with this changes?

**Comment by happy-san** [comment]
Hey @sanekyy Next version is not scheduled for any time soon. In the meantime, you can use the following in your `pubspec.yaml`
```dart
  typesense-dart:
    git:
      url: git://github.com/typesense/typesense-dart.git
```

**Pull request merged**
